### ISSUE TITLE
No Router Object created on fresh install. 

### ISSUE THREAD

**Issue by ms747** [routernetes/routernetes#1]
System install perfectly. But no router object is created [ waited for 1 hr ]  Hence no ip on lan interface.  Verified on physical desktop as well as on Virtual box [ wan connection - bridged mode, lan connection on internal network ]

**Comment by loganmc10** [comment]
First of all, I'd like to say thank you for being the first person to try this out!

Can you please share the output of: ```sudo systemctl status install-k3s``` and ```sudo journalctl -u install-k3s```?

You should hopefully be able to SSH in from the WAN side, or maybe if you have console access you could get it that way?

**Comment by loganmc10** [comment]
Closed due to no response
