### ISSUE TITLE
Wireguard?

### ISSUE THREAD

**Issue by KyleSanderson** [routernetes/routernetes#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by KyleSanderson** [comment]
lol. What? Are there docs or anything for this @loganmc10 ?

**Comment by loganmc10** [comment]
I need more than just one word and a question mark.

Additionally, this is a community project looking for volunteers. If you're looking for a new feature you'll need to contribute the code yourself, or provide funding for the feature to be added.

**Comment by KyleSanderson** [comment]
Saying unsupported is fine, asking for cash is another thing. Went from excitement to `move on` in a single swing.
